apiVersion: v1
kind: Secret
metadata:
  name: alert-secrets
  namespace: monitoring
type: Opaque
data:
  webhook: aHR0cHM6Ly9vcGVuLmZlaXNodS5jbi9vcGVuLWFwaXMvYm90L3YyL2hvb2svZTQzMjFkNTgtYzUyMS00ZDg5LTgzY2EtMGM2YmE2ZTAwMjRl
  deepseek-key: c2stZGVkNmYxYWMwZDI5NDg3Nzk0Y2RmYmRmOGU3NWQ3MmQ=